// let x = 23;
// console.log(typeof x);
// x = 'Poon';
// console.log(x);
// console.log(typeof x);
// y = new Date();
// console.log(y);
// console.log(typeof y);
// let a = NaN;
// console.log(typeof a + " NaN");
// let a = undefined;
// console.log(typeof a + " undefined");
// let b = a +1;
// console.log( b + " number");
// let a = Infinity;

let a = 0;
let b = "";
// c = a + b;
b == a ? console.log("True") : console.log("False");
console.log(typeof a + " of a = " + a );
